-- ========================================================================
-- SISTEMA INTEGRAL DE GESTIÓN DE CONTENEDORES & MÓDULOS
-- ACOSTA SERVICIOS S.R.L. / SG MONTAJES S.R.L. — BASE OPERATIVA TIMBÚES
-- ESQUEMA COMPLETO Y MIGRACIÓN IDEMPOTENTE PARA SUPABASE CLOUD
-- ========================================================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. TABLAS PRINCIPALES
-- 1. ELIMINAR TABLAS REDUNDANTES Y COLUMNAS OBSOLETAS
DROP TABLE IF EXISTS public.usuarios_contenedores CASCADE;

-- 2. TABLA UNIFICADA DE USUARIOS (SG MONTAJES & ACOSTA SERVICIOS)
CREATE TABLE IF NOT EXISTS public.usuarios (
    id TEXT PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL DEFAULT '123',
    nombre TEXT DEFAULT '',
    email TEXT DEFAULT '',
    role TEXT NOT NULL DEFAULT 'Solicitante',
    rubro_defecto TEXT NOT NULL DEFAULT 'Eléctrico',
    empresa TEXT NOT NULL DEFAULT 'SG MONTAJES SRL',
    permisos JSONB DEFAULT '[]'::jsonb,
    can_edit_prices BOOLEAN DEFAULT false,
    permisos_contenedores JSONB DEFAULT '[]'::jsonb,
    role_contenedores TEXT NOT NULL DEFAULT 'Consulta'
);

-- Asegurar columnas necesarias y eliminar columnas de vendedores solicitadas
ALTER TABLE public.usuarios ADD COLUMN IF NOT EXISTS nombre TEXT DEFAULT '';
ALTER TABLE public.usuarios ADD COLUMN IF NOT EXISTS email TEXT DEFAULT '';
ALTER TABLE public.usuarios ADD COLUMN IF NOT EXISTS role TEXT DEFAULT 'Solicitante';
ALTER TABLE public.usuarios ADD COLUMN IF NOT EXISTS rubro_defecto TEXT DEFAULT 'Eléctrico';
ALTER TABLE public.usuarios ADD COLUMN IF NOT EXISTS empresa TEXT DEFAULT 'SG MONTAJES SRL';
ALTER TABLE public.usuarios ADD COLUMN IF NOT EXISTS can_edit_prices BOOLEAN DEFAULT false;
ALTER TABLE public.usuarios ADD COLUMN IF NOT EXISTS permisos JSONB DEFAULT '[]'::jsonb;
ALTER TABLE public.usuarios ADD COLUMN IF NOT EXISTS permisos_contenedores JSONB DEFAULT '[]'::jsonb;
ALTER TABLE public.usuarios ADD COLUMN IF NOT EXISTS role_contenedores TEXT DEFAULT 'Consulta';

ALTER TABLE public.usuarios DROP COLUMN IF EXISTS vendedor_codigo;
ALTER TABLE public.usuarios DROP COLUMN IF EXISTS vendedor_nombre;

CREATE TABLE IF NOT EXISTS public.configuracion_contenedores (
    id BIGINT PRIMARY KEY DEFAULT 1,
    empresa TEXT NOT NULL DEFAULT 'ACOSTA SERVICIOS S.R.L.',
    cuit TEXT NOT NULL DEFAULT '30-71868621-7',
    iva TEXT DEFAULT 'Responsable Inscripto',
    deposito_principal TEXT DEFAULT 'Base Operativa — Timbúes',
    direccion TEXT DEFAULT 'Estanislao López, Timbúes, Santa Fe',
    email_notificaciones TEXT DEFAULT 'cotizaciones@sgmontajes.com.ar',
    telefono TEXT DEFAULT '(0341) 5890126',
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.contenedores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT UNIQUE NOT NULL,
    proveedor TEXT NOT NULL DEFAULT 'ACOSTA SERVICIOS SRL',
    tipo TEXT NOT NULL DEFAULT 'Oficina',
    medida TEXT NOT NULL DEFAULT '20''',
    estado TEXT NOT NULL DEFAULT 'empresa',
    pago TEXT DEFAULT 'al_dia',
    cliente TEXT DEFAULT '',
    ubicacion TEXT DEFAULT 'Base Operativa — Timbúes',
    lat DOUBLE PRECISION DEFAULT -32.6642,
    lng DOUBLE PRECISION DEFAULT -60.7932,
    entrega DATE,
    retiro DATE,
    monto TEXT DEFAULT '$ 250.000',
    obs_entrega TEXT DEFAULT '',
    obs_retiro TEXT DEFAULT '',
    tareas JSONB DEFAULT '[]'::jsonb,
    historial JSONB DEFAULT '[]'::jsonb,
    traslado TEXT NOT NULL DEFAULT 'no',
    traslado_monto TEXT DEFAULT '',
    traslado_horas TEXT DEFAULT '',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT chk_cont_estado CHECK (estado IN ('empresa', 'alquilado', 'reservado', 'reparacion')),
    CONSTRAINT chk_cont_pago CHECK (pago IN ('al_dia', 'pendiente', 'retrasado')),
    CONSTRAINT chk_cont_traslado CHECK (traslado IN ('si', 'no'))
);

CREATE TABLE IF NOT EXISTS public.seguimiento_contenedores (
    id TEXT PRIMARY KEY,
    code TEXT NOT NULL,
    tipo TEXT DEFAULT 'Oficina',
    medida TEXT DEFAULT '20''',
    proveedor TEXT NOT NULL DEFAULT 'ACOSTA SERVICIOS SRL',
    cliente TEXT NOT NULL DEFAULT '',
    fecha_salida DATE,
    hora_salida TEXT DEFAULT '',
    destino TEXT DEFAULT 'Obra',
    fecha_entrada DATE,
    hora_entrada TEXT DEFAULT '',
    retiro_estimado TEXT DEFAULT '',
    estado_movimiento TEXT NOT NULL DEFAULT 'en_obra',
    traslado TEXT NOT NULL DEFAULT 'no',
    traslado_monto TEXT DEFAULT '',
    traslado_horas TEXT DEFAULT '',
    observaciones TEXT DEFAULT '',
    remito_numero TEXT DEFAULT '',
    usuario TEXT DEFAULT 'admin',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT chk_mov_estado CHECK (estado_movimiento IN ('en_obra', 'en_base', 'transito')),
    CONSTRAINT chk_seg_traslado CHECK (traslado IN ('si', 'no'))
);

CREATE TABLE IF NOT EXISTS public.eventos_operativos (
    id TEXT PRIMARY KEY,
    tipo TEXT NOT NULL,
    descripcion TEXT NOT NULL,
    code TEXT,
    usuario TEXT DEFAULT 'Operador',
    hora TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. MIGRACIÓN IDEMPOTENTE (Por si las tablas ya existen)
ALTER TABLE public.contenedores ADD COLUMN IF NOT EXISTS proveedor TEXT DEFAULT 'ACOSTA SERVICIOS SRL';
ALTER TABLE public.contenedores ADD COLUMN IF NOT EXISTS traslado TEXT DEFAULT 'no';
ALTER TABLE public.contenedores ADD COLUMN IF NOT EXISTS traslado_monto TEXT DEFAULT '';
ALTER TABLE public.contenedores ADD COLUMN IF NOT EXISTS traslado_horas TEXT DEFAULT '';
ALTER TABLE public.contenedores ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now());

ALTER TABLE public.seguimiento_contenedores ADD COLUMN IF NOT EXISTS proveedor TEXT DEFAULT 'ACOSTA SERVICIOS SRL';
ALTER TABLE public.seguimiento_contenedores ADD COLUMN IF NOT EXISTS traslado TEXT DEFAULT 'no';
ALTER TABLE public.seguimiento_contenedores ADD COLUMN IF NOT EXISTS traslado_monto TEXT DEFAULT '';
ALTER TABLE public.seguimiento_contenedores ADD COLUMN IF NOT EXISTS traslado_horas TEXT DEFAULT '';
ALTER TABLE public.seguimiento_contenedores ADD COLUMN IF NOT EXISTS retiro_estimado TEXT DEFAULT '';
ALTER TABLE public.seguimiento_contenedores ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now());

-- 3. TRIGGERS UPDATED_AT
CREATE OR REPLACE FUNCTION public.actualizar_timestamp_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = timezone('utc'::text, now());
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_actualizar_contenedores ON public.contenedores;
CREATE TRIGGER trg_actualizar_contenedores
    BEFORE UPDATE ON public.contenedores
    FOR EACH ROW EXECUTE FUNCTION public.actualizar_timestamp_updated_at();

DROP TRIGGER IF EXISTS trg_actualizar_seguimiento ON public.seguimiento_contenedores;
CREATE TRIGGER trg_actualizar_seguimiento
    BEFORE UPDATE ON public.seguimiento_contenedores
    FOR EACH ROW EXECUTE FUNCTION public.actualizar_timestamp_updated_at();

-- 4. ÍNDICES
CREATE INDEX IF NOT EXISTS idx_contenedores_code ON public.contenedores(code);
CREATE INDEX IF NOT EXISTS idx_contenedores_estado ON public.contenedores(estado);
CREATE INDEX IF NOT EXISTS idx_contenedores_proveedor ON public.contenedores(proveedor);
CREATE INDEX IF NOT EXISTS idx_contenedores_cliente ON public.contenedores(cliente);
CREATE INDEX IF NOT EXISTS idx_contenedores_traslado ON public.contenedores(traslado);

CREATE INDEX IF NOT EXISTS idx_seguimiento_code ON public.seguimiento_contenedores(code);
CREATE INDEX IF NOT EXISTS idx_seguimiento_cliente ON public.seguimiento_contenedores(cliente);
CREATE INDEX IF NOT EXISTS idx_seguimiento_proveedor ON public.seguimiento_contenedores(proveedor);
CREATE INDEX IF NOT EXISTS idx_seguimiento_estado ON public.seguimiento_contenedores(estado_movimiento);
CREATE INDEX IF NOT EXISTS idx_seguimiento_fechas ON public.seguimiento_contenedores(fecha_salida, fecha_entrada);

ALTER TABLE public.usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.configuracion_contenedores ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contenedores ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.seguimiento_contenedores ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.eventos_operativos ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Acceso completo a Contenedores" ON public.contenedores;
CREATE POLICY "Acceso completo a Contenedores" ON public.contenedores FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Acceso completo a Seguimiento" ON public.seguimiento_contenedores;
CREATE POLICY "Acceso completo a Seguimiento" ON public.seguimiento_contenedores FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Acceso completo a Configuración" ON public.configuracion_contenedores;
CREATE POLICY "Acceso completo a Configuración" ON public.configuracion_contenedores FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Acceso completo a Usuarios" ON public.usuarios;
DROP POLICY IF EXISTS "Permitir acceso usuarios" ON public.usuarios;
CREATE POLICY "Acceso completo a Usuarios" ON public.usuarios FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Acceso completo a Eventos" ON public.eventos_operativos;
CREATE POLICY "Acceso completo a Eventos" ON public.eventos_operativos FOR ALL USING (true) WITH CHECK (true);

-- 6. REALTIME
DO $$
BEGIN
    BEGIN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.contenedores;
    EXCEPTION WHEN OTHERS THEN NULL;
    END;
    BEGIN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.seguimiento_contenedores;
    EXCEPTION WHEN OTHERS THEN NULL;
    END;
    BEGIN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.eventos_operativos;
    EXCEPTION WHEN OTHERS THEN NULL;
    END;
    BEGIN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.usuarios;
    EXCEPTION WHEN OTHERS THEN NULL;
    END;
END $$;

-- 7. VISTAS
CREATE OR REPLACE VIEW public.vista_seguimiento_salidas_activas AS
SELECT 
    s.id, s.code, s.tipo, s.medida, s.proveedor, s.cliente, s.destino,
    s.fecha_salida, s.hora_salida, s.retiro_estimado, s.traslado,
    s.traslado_monto, s.traslado_horas, s.remito_numero, s.usuario,
    c.estado AS estado_flota_actual, c.pago AS estado_pago
FROM public.seguimiento_contenedores s
LEFT JOIN public.contenedores c ON s.code = c.code
WHERE s.estado_movimiento = 'en_obra' OR s.fecha_entrada IS NULL;

CREATE OR REPLACE VIEW public.vista_resumen_proveedor_estado AS
SELECT 
    proveedor, estado, COUNT(*) AS cantidad,
    COUNT(*) FILTER (WHERE traslado = 'si') AS con_traslado
FROM public.contenedores
GROUP BY proveedor, estado;

-- 8. CONFIGURACIÓN Y USUARIOS
INSERT INTO public.configuracion_contenedores (id, empresa, cuit, iva, deposito_principal, direccion, email_notificaciones, telefono)
VALUES (1, 'ACOSTA SERVICIOS S.R.L.', '30-71868621-7', 'Responsable Inscripto', 'Base Operativa — Timbúes', 'Estanislao López, Timbúes, Santa Fe', 'cotizaciones@sgmontajes.com.ar', '(0341) 5890126')
ON CONFLICT (id) DO UPDATE SET
    empresa = EXCLUDED.empresa, cuit = EXCLUDED.cuit,
    deposito_principal = EXCLUDED.deposito_principal,
    direccion = EXCLUDED.direccion,
    email_notificaciones = EXCLUDED.email_notificaciones,
    telefono = EXCLUDED.telefono;

-- 8. USUARIOS UNIFICADOS (PRESUPUESTOS & CONTENEDORES)
-- Migración automática si existía la tabla previa usuarios_contenedores
INSERT INTO public.usuarios (id, username, password, nombre, email, role, rubro_defecto, empresa, can_edit_prices, permisos, permisos_contenedores)
VALUES 
    ('1', 'mel', '123', 'Mel', 'mel@empresa.com', 'Administrador', 'Eléctrico', 'SG MONTAJES SRL', true, 
     '["menu-ingresar", "menu-all", "menu-estado-presupuesto", "menu-rechazados", "menu-admin", "menu-facturacion", "menu-all-ver", "menu-all-edit", "menu-ingresar-edit-price", "edit-precios"]'::jsonb, 
     '["ver_flota", "editar_flota", "editar_alquileres", "editar_seguimiento", "editar_taller", "ver_configuracion", "ver_supabase"]'::jsonb),

    ('2', 'juanluis', '123', 'Juan Luis', 'grandijuanluis@gmail.com', 'Solicitante', 'Eléctrico', 'SG MONTAJES SRL', false, 
     '["menu-ingresar", "menu-all", "menu-estado-presupuesto", "menu-rechazados", "menu-facturacion", "menu-all-ver", "menu-all-edit"]'::jsonb, 
     '["ver_flota"]'::jsonb),

    ('3', 'luciano', '123', 'Luciano', 'luciano@sgmontajes.com', 'Solicitante', 'Eléctrico', 'SG MONTAJES SRL', false, 
     '["menu-ingresar", "menu-all", "menu-estado-presupuesto", "menu-rechazados", "menu-facturacion", "menu-all-ver", "menu-all-edit"]'::jsonb, 
     '["ver_flota"]'::jsonb),

    ('4', 'roberto', '123', 'Roberto', 'Roberto@sgmontajes.com', 'Solicitante', 'Mecánico', 'SG MONTAJES SRL', false, 
     '["menu-ingresar", "menu-all", "menu-estado-presupuesto", "menu-rechazados", "menu-facturacion", "menu-all-ver", "menu-all-edit"]'::jsonb, 
     '["ver_flota"]'::jsonb),

    ('5', 'melani', '123', 'Melani Grandi', 'melanidaiana28@gmail.com', 'Administrador', 'Eléctrico', 'SG MONTAJES SRL', true, 
     '["menu-ingresar", "menu-all", "menu-estado-presupuesto", "menu-rechazados", "menu-admin", "menu-facturacion", "menu-all-ver", "menu-all-edit", "menu-ingresar-edit-price", "edit-precios"]'::jsonb, 
     '["ver_flota", "editar_flota", "editar_alquileres", "editar_seguimiento", "editar_taller", "ver_configuracion", "ver_supabase"]'::jsonb),

    ('6', 'nicole', '123', 'Nicole', 'nicole@sgmontajes.com', 'Solicitante', 'Eléctrico', 'SG MONTAJES SRL', false, 
     '["menu-facturacion"]'::jsonb, 
     '["ver_flota", "editar_seguimiento"]'::jsonb),

    ('7', 'alexis', '123', 'Alexis', 'alexis@sgmontajes.com', 'Solicitante', 'Mecánico', 'SG MONTAJES SRL', false, 
     '["menu-ingresar", "menu-all", "menu-estado-presupuesto", "menu-rechazados", "menu-facturacion", "menu-all-ver", "menu-all-edit"]'::jsonb, 
     '["ver_flota"]'::jsonb),

    ('8', 'emiliano', '123', 'Emiliano', 'emiliano@sgmontajes.com', 'Solicitante', 'Eléctrico', 'SG MONTAJES SRL', false, 
     '["menu-ingresar", "menu-all", "menu-estado-presupuesto", "menu-rechazados", "menu-facturacion", "menu-all-ver", "menu-all-edit"]'::jsonb, 
     '["ver_flota"]'::jsonb),

    ('9', 'hernan', '123', 'Hernán', 'hernan@sgmontajes.com', 'Solicitante', 'Eléctrico', 'SG MONTAJES SRL', false, 
     '["menu-ingresar", "menu-all", "menu-estado-presupuesto", "menu-rechazados", "menu-facturacion", "menu-all-ver", "menu-all-edit"]'::jsonb, 
     '["ver_flota"]'::jsonb),

    ('10', 'admin', '123', 'Administrador General', 'cotizaciones@sgmontajes.com.ar', 'Administrador', 'Eléctrico', 'SG MONTAJES SRL', true, 
     '["menu-ingresar", "menu-all", "menu-estado-presupuesto", "menu-rechazados", "menu-admin", "menu-facturacion", "menu-all-ver", "menu-all-edit", "menu-ingresar-edit-price", "edit-precios"]'::jsonb, 
     '["ver_flota", "editar_flota", "editar_alquileres", "editar_seguimiento", "editar_taller", "ver_configuracion", "ver_supabase"]'::jsonb),

    ('11', 'logistica', '123', 'Operador Logística', 'logistica@sgmontajes.com.ar', 'Solicitante', 'Eléctrico', 'ACOSTA SERVICIOS SRL', false, 
     '["menu-all-ver"]'::jsonb, 
     '["ver_flota", "editar_flota", "editar_alquileres", "editar_seguimiento", "editar_taller"]'::jsonb),

    ('12', 'seguimiento', '123', 'Operadora de Seguimiento', 'seguimiento@sgmontajes.com.ar', 'Solicitante', 'Eléctrico', 'ACOSTA SERVICIOS SRL', false, 
     '["menu-all-ver"]'::jsonb, 
     '["ver_flota", "editar_seguimiento"]'::jsonb),

    ('13', 'consulta', '123', 'Usuario Consulta', 'consulta@sgmontajes.com.ar', 'Solicitante', 'Eléctrico', 'SG MONTAJES SRL', false, 
     '["menu-all-ver"]'::jsonb, 
     '["ver_flota"]'::jsonb)
ON CONFLICT (username) DO UPDATE SET
    nombre = EXCLUDED.nombre,
    email = EXCLUDED.email,
    role = EXCLUDED.role,
    permisos = EXCLUDED.permisos,
    permisos_contenedores = EXCLUDED.permisos_contenedores,
    can_edit_prices = EXCLUDED.can_edit_prices,
    rubro_defecto = EXCLUDED.rubro_defecto;

-- 9. CARGA DE LAS 51 UNIDADES DE LA FLOTA
INSERT INTO public.contenedores (code, proveedor, tipo, medida, estado, pago, cliente, ubicacion, lat, lng, entrega, retiro, monto, obs_entrega, obs_retiro, tareas, historial, traslado, traslado_monto, traslado_horas)
VALUES 
  ('C-101', 'SG MONTAJES SRL', 'Oficina', '20''', 'alquilado', 'retrasado', 'Obra Puerto Norte', 'Av. Calchaquí 5600, Quilmes', -34.7415, -58.2733, '2026-04-21', '2026-09-20', '$ 250.000', '', '', '[]'::jsonb, '[{"fecha": "2026-04-21", "accion": "Asignación inicial", "cliente": "Obra Puerto Norte", "ubicacion": "Av. Calchaquí 5600, Quilmes", "estado": "alquilado"}]'::jsonb, 'no', '', ''),
  ('C-102', 'ACOSTA SERVICIOS SRL', 'Oficina', '10''', 'alquilado', 'al_dia', 'Ingeniería Delta', 'Av. Circunvalación 900, Luján', -34.5701, -59.1053, '2026-07-21', '2026-10-14', '$ 250.000', 'Entregado con 2 llaves, aire funcionando, piso sin marcas.', '', '["Sellar filtración de techo"]'::jsonb, '[{"fecha": "2026-07-21", "accion": "Asignación inicial", "cliente": "Ingeniería Delta", "ubicacion": "Av. Circunvalación 900, Luján", "estado": "alquilado"}]'::jsonb, 'no', '', ''),
  ('C-103', 'SG MONTAJES SRL', 'Pañol', '20''', 'alquilado', 'al_dia', 'Consorcio Ruta 9', 'Av. Circunvalación 900, Luján', -34.5701, -59.1053, '2026-06-18', '2026-11-16', '$ 250.000', '', '', '[]'::jsonb, '[{"fecha": "2026-06-18", "accion": "Asignación inicial", "cliente": "Consorcio Ruta 9", "ubicacion": "Av. Circunvalación 900, Luján", "estado": "alquilado"}]'::jsonb, 'no', '', ''),
  ('C-104', 'ACOSTA SERVICIOS SRL', 'Comedor', '40''', 'alquilado', 'al_dia', 'Constructora Riolar', 'Ruta 6 Km 118, Cañuelas', -35.0501, -58.7594, '2025-12-19', '2026-11-02', '$ 250.000', 'Entregado con 2 llaves, aire funcionando, piso sin marcas.', '', '[]'::jsonb, '[{"fecha": "2025-12-19", "accion": "Asignación inicial", "cliente": "Constructora Riolar", "ubicacion": "Ruta 6 Km 118, Cañuelas", "estado": "alquilado"}]'::jsonb, 'no', '', ''),
  ('C-105', 'SG MONTAJES SRL', 'Pañol', '40''', 'alquilado', 'retrasado', 'Metalúrgica Sanz', 'Ruta 6 Km 118, Cañuelas', -35.0501, -58.7594, '2026-05-21', '2026-09-23', '$ 250.000', '', '', '["Pintura exterior"]'::jsonb, '[{"fecha": "2026-05-21", "accion": "Asignación inicial", "cliente": "Metalúrgica Sanz", "ubicacion": "Ruta 6 Km 118, Cañuelas", "estado": "alquilado"}]'::jsonb, 'no', '', ''),
  ('C-106', 'ACOSTA SERVICIOS SRL', 'Pañol', '20''', 'alquilado', 'al_dia', 'Tecnorural SRL', 'Av. Calchaquí 5600, Quilmes', -34.7415, -58.2733, '2026-04-22', '2026-08-31', '$ 250.000', 'Entregado con 2 llaves, aire funcionando, piso sin marcas.', '', '["Cambiar aire acondicionado"]'::jsonb, '[{"fecha": "2026-04-22", "accion": "Asignación inicial", "cliente": "Tecnorural SRL", "ubicacion": "Av. Calchaquí 5600, Quilmes", "estado": "alquilado"}]'::jsonb, 'no', '', ''),
  ('C-107', 'SG MONTAJES SRL', 'Comedor', '10''', 'alquilado', 'retrasado', 'Consorcio Ruta 9', 'Camino Centenario 2200, La Plata', -34.9021, -57.9789, '2026-03-30', '2026-09-29', '$ 250.000', '', '', '[]'::jsonb, '[{"fecha": "2026-03-30", "accion": "Asignación inicial", "cliente": "Consorcio Ruta 9", "ubicacion": "Camino Centenario 2200, La Plata", "estado": "alquilado"}]'::jsonb, 'no', '', ''),
  ('C-108', 'ACOSTA SERVICIOS SRL', 'Comedor', '10''', 'alquilado', 'al_dia', 'Tecnorural SRL', 'Av. Calchaquí 5600, Quilmes', -34.7415, -58.2733, '2026-04-05', '2026-09-21', '$ 250.000', 'Entregado con 2 llaves, aire funcionando, piso sin marcas.', '', '[]'::jsonb, '[{"fecha": "2026-04-05", "accion": "Asignación inicial", "cliente": "Tecnorural SRL", "ubicacion": "Av. Calchaquí 5600, Quilmes", "estado": "alquilado"}]'::jsonb, 'no', '', ''),
  ('C-109', 'SG MONTAJES SRL', 'Oficina', '40''', 'empresa', 'al_dia', '', 'Base Operativa — Timbúes', -32.6642, -60.7932, NULL, NULL, '$ 250.000', '', '', '[]'::jsonb, '[]'::jsonb, 'no', '', ''),
  ('C-110', 'ACOSTA SERVICIOS SRL', 'Comedor', '10''', 'reservado', 'al_dia', 'Áridos del Sur', 'Base Operativa — Timbúes', -32.6642, -60.7932, NULL, NULL, '$ 250.000', '', '', '["Sellar filtración de techo"]'::jsonb, '[{"fecha": "2026-01-01", "accion": "Asignación inicial", "cliente": "Áridos del Sur", "ubicacion": "Base Operativa — Timbúes", "estado": "reservado"}]'::jsonb, 'no', '', ''),
  ('C-111', 'SG MONTAJES SRL', 'Pañol', '10''', 'empresa', 'al_dia', '', 'Base Operativa — Timbúes', -32.6642, -60.7932, NULL, NULL, '$ 250.000', '', '', '[]'::jsonb, '[]'::jsonb, 'no', '', ''),
  ('C-112', 'ACOSTA SERVICIOS SRL', 'Comedor', '20''', 'alquilado', 'al_dia', 'Ingeniería Delta', 'Av. Calchaquí 5600, Quilmes', -34.7415, -58.2733, '2026-03-12', '2026-09-23', '$ 250.000', '', '', '["Limpieza profunda", "Pintura exterior"]'::jsonb, '[{"fecha": "2026-03-12", "accion": "Asignación inicial", "cliente": "Ingeniería Delta", "ubicacion": "Av. Calchaquí 5600, Quilmes", "estado": "alquilado"}]'::jsonb, 'no', '', ''),
  ('C-113', 'SG MONTAJES SRL', 'Comedor', '40''', 'empresa', 'al_dia', '', 'Base Operativa — Timbúes', -32.6642, -60.7932, NULL, NULL, '$ 250.000', '', '', '[]'::jsonb, '[]'::jsonb, 'no', '', ''),
  ('C-114', 'ACOSTA SERVICIOS SRL', 'Comedor', '40''', 'alquilado', 'al_dia', 'Ingeniería Delta', 'Av. Circunvalación 900, Luján', -34.5701, -59.1053, '2025-12-11', '2026-09-08', '$ 250.000', '', '', '[]'::jsonb, '[{"fecha": "2025-12-11", "accion": "Asignación inicial", "cliente": "Ingeniería Delta", "ubicacion": "Av. Circunvalación 900, Luján", "estado": "alquilado"}]'::jsonb, 'no', '', ''),
  ('C-115', 'SG MONTAJES SRL', 'Oficina', '20''', 'reparacion', 'al_dia', '', 'Taller propio — Timbúes', -32.6642, -60.7932, NULL, NULL, '$ 250.000', '', '', '["Reparar piso", "Cambiar cerradura"]'::jsonb, '[]'::jsonb, 'no', '', ''),
  ('C-116', 'ACOSTA SERVICIOS SRL', 'Comedor', '10''', 'alquilado', 'retrasado', 'Áridos del Sur', 'Ruta 6 Km 118, Cañuelas', -35.0501, -58.7594, '2026-04-05', '2026-09-13', '$ 250.000', '', '', '[]'::jsonb, '[{"fecha": "2026-04-05", "accion": "Asignación inicial", "cliente": "Áridos del Sur", "ubicacion": "Ruta 6 Km 118, Cañuelas", "estado": "alquilado"}]'::jsonb, 'no', '', ''),
  ('C-117', 'SG MONTAJES SRL', 'Pañol', '40''', 'empresa', 'al_dia', '', 'Base Operativa — Timbúes', -32.6642, -60.7932, NULL, NULL, '$ 250.000', '', '', '["Cambiar luminaria", "Cambiar cerradura"]'::jsonb, '[]'::jsonb, 'no', '', ''),
  ('C-118', 'ACOSTA SERVICIOS SRL', 'Comedor', '10''', 'reservado', 'al_dia', 'Ingeniería Delta', 'Base Operativa — Timbúes', -32.6642, -60.7932, NULL, NULL, '$ 250.000', '', '', '["Reparar puerta"]'::jsonb, '[{"fecha": "2026-01-01", "accion": "Asignación inicial", "cliente": "Ingeniería Delta", "ubicacion": "Base Operativa — Timbúes", "estado": "reservado"}]'::jsonb, 'no', '', ''),
  ('C-119', 'SG MONTAJES SRL', 'Pañol', '40''', 'reparacion', 'al_dia', '', 'Taller propio — Timbúes', -32.6642, -60.7932, NULL, NULL, '$ 250.000', '', '', '[]'::jsonb, '[]'::jsonb, 'no', '', ''),
  ('C-120', 'ACOSTA SERVICIOS SRL', 'Oficina', '40''', 'empresa', 'al_dia', '', 'Base Operativa — Timbúes', -32.6642, -60.7932, NULL, NULL, '$ 250.000', '', '', '[]'::jsonb, '[]'::jsonb, 'no', '', ''),
  ('C-121', 'SG MONTAJES SRL', 'Pañol', '10''', 'reparacion', 'al_dia', '', 'Taller propio — Timbúes', -32.6642, -60.7932, NULL, NULL, '$ 250.000', '', '', '[]'::jsonb, '[]'::jsonb, 'no', '', ''),
  ('C-122', 'ACOSTA SERVICIOS SRL', 'Comedor', '10''', 'reservado', 'al_dia', 'Minera Cerro Azul', 'Base Operativa — Timbúes', -32.6642, -60.7932, NULL, NULL, '$ 250.000', '', '', '[]'::jsonb, '[{"fecha": "2026-01-01", "accion": "Asignación inicial", "cliente": "Minera Cerro Azul", "ubicacion": "Base Operativa — Timbúes", "estado": "reservado"}]'::jsonb, 'no', '', ''),
  ('C-123', 'SG MONTAJES SRL', 'Comedor', '20''', 'alquilado', 'al_dia', 'Obra Vial Km 42', 'Parque Industrial Tigre, Nave 3', -34.4198, -58.6032, '2026-02-01', '2026-08-26', '$ 250.000', '', '', '[]'::jsonb, '[{"fecha": "2026-02-01", "accion": "Asignación inicial", "cliente": "Obra Vial Km 42", "ubicacion": "Parque Industrial Tigre, Nave 3", "estado": "alquilado"}]'::jsonb, 'no', '', ''),
  ('C-124', 'ACOSTA SERVICIOS SRL', 'Oficina', '10''', 'alquilado', 'al_dia', 'Ingeniería Delta', 'Puerto Nuevo, Dársena D, CABA', -34.5723, -58.3708, '2025-12-18', '2026-08-28', '$ 250.000', 'Entregado con 2 llaves, aire funcionando, piso sin marcas.', '', '["Pintura exterior"]'::jsonb, '[{"fecha": "2025-12-18", "accion": "Asignación inicial", "cliente": "Ingeniería Delta", "ubicacion": "Puerto Nuevo, Dársena D, CABA", "estado": "alquilado"}]'::jsonb, 'no', '', ''),
  ('C-125', 'SG MONTAJES SRL', 'Comedor', '20''', 'alquilado', 'al_dia', 'Minera Cerro Azul', 'Puerto Nuevo, Dársena D, CABA', -34.5723, -58.3708, '2025-12-24', '2026-09-22', '$ 250.000', 'Entregado con 2 llaves, aire funcionando, piso sin marcas.', '', '[]'::jsonb, '[{"fecha": "2025-12-24", "accion": "Asignación inicial", "cliente": "Minera Cerro Azul", "ubicacion": "Puerto Nuevo, Dársena D, CABA", "estado": "alquilado"}]'::jsonb, 'no', '', ''),
  ('C-126', 'ACOSTA SERVICIOS SRL', 'Comedor', '20''', 'alquilado', 'al_dia', 'Ingeniería Delta', 'Ruta 9 Km 42, Escobar', -34.3486, -58.7931, '2026-01-14', '2026-09-27', '$ 250.000', '', '', '["Limpieza profunda"]'::jsonb, '[{"fecha": "2026-01-14", "accion": "Asignación inicial", "cliente": "Ingeniería Delta", "ubicacion": "Ruta 9 Km 42, Escobar", "estado": "alquilado"}]'::jsonb, 'no', '', ''),
  ('C-127', 'SG MONTAJES SRL', 'Pañol', '20''', 'alquilado', 'retrasado', 'Constructora Riolar', 'Ruta 9 Km 42, Escobar', -34.3486, -58.7931, '2026-03-27', '2026-08-20', '$ 250.000', '', '', '[]'::jsonb, '[{"fecha": "2026-03-27", "accion": "Asignación inicial", "cliente": "Constructora Riolar", "ubicacion": "Ruta 9 Km 42, Escobar", "estado": "alquilado"}]'::jsonb, 'no', '', ''),
  ('C-128', 'ACOSTA SERVICIOS SRL', 'Oficina', '20''', 'empresa', 'al_dia', '', 'Base Operativa — Timbúes', -32.6642, -60.7932, NULL, NULL, '$ 250.000', '', '', '[]'::jsonb, '[]'::jsonb, 'no', '', ''),
  ('C-129', 'SG MONTAJES SRL', 'Oficina', '40''', 'reparacion', 'al_dia', '', 'Taller propio — Timbúes', -32.6642, -60.7932, NULL, NULL, '$ 250.000', '', '', '["Cambiar cerradura"]'::jsonb, '[]'::jsonb, 'no', '', ''),
  ('C-130', 'ACOSTA SERVICIOS SRL', 'Pañol', '20''', 'alquilado', 'al_dia', 'Consorcio Ruta 9', 'Parque Industrial Tigre, Nave 3', -34.4198, -58.6032, '2025-12-11', '2026-10-14', '$ 250.000', '', '', '["Limpieza profunda"]'::jsonb, '[{"fecha": "2025-12-11", "accion": "Asignación inicial", "cliente": "Consorcio Ruta 9", "ubicacion": "Parque Industrial Tigre, Nave 3", "estado": "alquilado"}]'::jsonb, 'no', '', ''),
  ('C-131', 'SG MONTAJES SRL', 'Pañol', '20''', 'empresa', 'al_dia', '', 'Base Operativa — Timbúes', -32.6642, -60.7932, NULL, NULL, '$ 250.000', '', '', '[]'::jsonb, '[]'::jsonb, 'no', '', ''),
  ('C-132', 'ACOSTA SERVICIOS SRL', 'Pañol', '40''', 'alquilado', 'al_dia', 'Constructora Riolar', 'Ruta 9 Km 42, Escobar', -34.3486, -58.7931, '2025-12-18', '2026-09-02', '$ 250.000', '', '', '[]'::jsonb, '[{"fecha": "2025-12-18", "accion": "Asignación inicial", "cliente": "Constructora Riolar", "ubicacion": "Ruta 9 Km 42, Escobar", "estado": "alquilado"}]'::jsonb, 'no', '', ''),
  ('C-133', 'SG MONTAJES SRL', 'Pañol', '10''', 'alquilado', 'al_dia', 'Tecnorural SRL', 'Av. Calchaquí 5600, Quilmes', -34.7415, -58.2733, '2026-07-01', '2026-11-06', '$ 250.000', 'Entregado con 2 llaves, aire funcionando, piso sin marcas.', '', '[]'::jsonb, '[{"fecha": "2026-07-01", "accion": "Asignación inicial", "cliente": "Tecnorural SRL", "ubicacion": "Av. Calchaquí 5600, Quilmes", "estado": "alquilado"}]'::jsonb, 'no', '', ''),
  ('C-134', 'ACOSTA SERVICIOS SRL', 'Comedor', '40''', 'empresa', 'al_dia', '', 'Base Operativa — Timbúes', -32.6642, -60.7932, NULL, NULL, '$ 250.000', '', '', '["Sellar filtración de techo"]'::jsonb, '[]'::jsonb, 'no', '', ''),
  ('C-135', 'SG MONTAJES SRL', 'Comedor', '20''', 'alquilado', 'al_dia', 'Obra Puerto Norte', 'Ruta 9 Km 42, Escobar', -34.3486, -58.7931, '2026-01-09', '2026-11-17', '$ 250.000', 'Entregado con 2 llaves, aire funcionando, piso sin marcas.', '', '[]'::jsonb, '[{"fecha": "2026-01-09", "accion": "Asignación inicial", "cliente": "Obra Puerto Norte", "ubicacion": "Ruta 9 Km 42, Escobar", "estado": "alquilado"}]'::jsonb, 'no', '', ''),
  ('C-136', 'ACOSTA SERVICIOS SRL', 'Pañol', '20''', 'reparacion', 'al_dia', '', 'Taller propio — Timbúes', -32.6642, -60.7932, NULL, NULL, '$ 250.000', '', '', '[]'::jsonb, '[]'::jsonb, 'no', '', ''),
  ('C-137', 'ACOSTA SERVICIOS SRL', 'Oficina', '20''', 'alquilado', 'al_dia', 'Tecnorural SRL', 'Av. Calchaquí 5600, Quilmes', -34.7415, -58.2733, '2026-01-20', '2026-09-23', '$ 250.000', 'Entregado con 2 llaves, aire funcionando, piso sin marcas.', '', '[]'::jsonb, '[{"fecha": "2026-01-20", "accion": "Asignación inicial", "cliente": "Tecnorural SRL", "ubicacion": "Av. Calchaquí 5600, Quilmes", "estado": "alquilado"}]'::jsonb, 'no', '', ''),
  ('C-138', 'ACOSTA SERVICIOS SRL', 'Oficina', '20''', 'alquilado', 'al_dia', 'Ingeniería Delta', 'Av. Calchaquí 5600, Quilmes', -34.7415, -58.2733, '2026-01-29', '2026-09-15', '$ 250.000', 'Entregado con 2 llaves, aire funcionando, piso sin marcas.', '', '[]'::jsonb, '[{"fecha": "2026-01-29", "accion": "Asignación inicial", "cliente": "Ingeniería Delta", "ubicacion": "Av. Calchaquí 5600, Quilmes", "estado": "alquilado"}]'::jsonb, 'no', '', ''),
  ('C-139', 'ACOSTA SERVICIOS SRL', 'Oficina', '10''', 'empresa', 'al_dia', '', 'Base Operativa — Timbúes', -32.6642, -60.7932, NULL, NULL, '$ 250.000', '', '', '[]'::jsonb, '[]'::jsonb, 'no', '', ''),
  ('C-140', 'ACOSTA SERVICIOS SRL', 'Pañol', '10''', 'alquilado', 'al_dia', 'Minera Cerro Azul', 'Parque Industrial Tigre, Nave 3', -34.4198, -58.6032, '2026-05-25', '2026-08-21', '$ 250.000', '', '', '[]'::jsonb, '[{"fecha": "2026-05-25", "accion": "Asignación inicial", "cliente": "Minera Cerro Azul", "ubicacion": "Parque Industrial Tigre, Nave 3", "estado": "alquilado"}]'::jsonb, 'no', '', ''),
  ('C-141', 'ACOSTA SERVICIOS SRL', 'Oficina', '20''', 'reservado', 'al_dia', 'Minera Cerro Azul', 'Base Operativa — Timbúes', -32.6642, -60.7932, NULL, NULL, '$ 250.000', '', '', '[]'::jsonb, '[{"fecha": "2026-01-01", "accion": "Asignación inicial", "cliente": "Minera Cerro Azul", "ubicacion": "Base Operativa — Timbúes", "estado": "reservado"}]'::jsonb, 'no', '', ''),
  ('C-142', 'ACOSTA SERVICIOS SRL', 'Pañol', '20''', 'alquilado', 'al_dia', 'Ingeniería Delta', 'Ruta 6 Km 118, Cañuelas', -35.0501, -58.7594, '2026-01-17', '2026-11-09', '$ 250.000', '', '', '[]'::jsonb, '[{"fecha": "2026-01-17", "accion": "Asignación inicial", "cliente": "Ingeniería Delta", "ubicacion": "Ruta 6 Km 118, Cañuelas", "estado": "alquilado"}]'::jsonb, 'no', '', ''),
  ('C-143', 'ACOSTA SERVICIOS SRL', 'Pañol', '20''', 'alquilado', 'al_dia', 'Ingeniería Delta', 'Parque Industrial Pilar, Lote 7', -34.4587, -58.9142, '2026-08-05', '2026-10-21', '$ 250.000', 'Entregado con 2 llaves, aire funcionando, piso sin marcas.', '', '[]'::jsonb, '[{"fecha": "2026-08-05", "accion": "Asignación inicial", "cliente": "Ingeniería Delta", "ubicacion": "Parque Industrial Pilar, Lote 7", "estado": "alquilado"}]'::jsonb, 'no', '', ''),
  ('C-144', 'ACOSTA SERVICIOS SRL', 'Comedor', '10''', 'alquilado', 'retrasado', 'Ingeniería Delta', 'Ruta 9 Km 42, Escobar', -34.3486, -58.7931, '2025-12-17', '2026-10-25', '$ 250.000', 'Entregado con 2 llaves, aire funcionando, piso sin marcas.', '', '["Pintura exterior"]'::jsonb, '[{"fecha": "2025-12-17", "accion": "Asignación inicial", "cliente": "Ingeniería Delta", "ubicacion": "Ruta 9 Km 42, Escobar", "estado": "alquilado"}]'::jsonb, 'no', '', ''),
  ('C-145', 'ACOSTA SERVICIOS SRL', 'Pañol', '10''', 'empresa', 'al_dia', '', 'Base Operativa — Timbúes', -32.6642, -60.7932, NULL, NULL, '$ 250.000', '', '', '[]'::jsonb, '[]'::jsonb, 'no', '', ''),
  ('C-146', 'ACOSTA SERVICIOS SRL', 'Pañol', '10''', 'alquilado', 'al_dia', 'Constructora Riolar', 'Parque Industrial Pilar, Lote 7', -34.4587, -58.9142, '2026-06-23', '2026-10-18', '$ 250.000', 'Entregado con 2 llaves, aire funcionando, piso sin marcas.', '', '[]'::jsonb, '[{"fecha": "2026-06-23", "accion": "Asignación inicial", "cliente": "Constructora Riolar", "ubicacion": "Parque Industrial Pilar, Lote 7", "estado": "alquilado"}]'::jsonb, 'no', '', ''),
  ('C-147', 'ACOSTA SERVICIOS SRL', 'Pañol', '20''', 'alquilado', 'al_dia', 'Metalúrgica Sanz', 'Ruta 6 Km 118, Cañuelas', -35.0501, -58.7594, '2026-02-19', '2026-08-27', '$ 250.000', 'Entregado con 2 llaves, aire funcionando, piso sin marcas.', '', '["Reparar aire acondicionado", "Revisión eléctrica"]'::jsonb, '[{"fecha": "2026-02-19", "accion": "Asignación inicial", "cliente": "Metalúrgica Sanz", "ubicacion": "Ruta 6 Km 118, Cañuelas", "estado": "alquilado"}]'::jsonb, 'no', '', ''),
  ('C-148', 'ACOSTA SERVICIOS SRL', 'Comedor', '40''', 'alquilado', 'al_dia', 'Obra Puerto Norte', 'Av. Mitre 3400, Avellaneda', -34.6634, -58.3651, '2026-03-02', '2026-08-29', '$ 250.000', '', '', '[]'::jsonb, '[{"fecha": "2026-03-02", "accion": "Asignación inicial", "cliente": "Obra Puerto Norte", "ubicacion": "Av. Mitre 3400, Avellaneda", "estado": "alquilado"}]'::jsonb, 'no', '', ''),
  ('C-149', 'ACOSTA SERVICIOS SRL', 'Comedor', '20''', 'empresa', 'al_dia', '', 'Base Operativa — Timbúes', -32.6642, -60.7932, NULL, NULL, '$ 250.000', '', '', '[]'::jsonb, '[]'::jsonb, 'no', '', ''),
  ('C-150', 'ACOSTA SERVICIOS SRL', 'Pañol', '20''', 'reservado', 'al_dia', 'Áridos del Sur', 'Base Operativa — Timbúes', -32.6642, -60.7932, NULL, NULL, '$ 250.000', '', '', '["Limpieza profunda"]'::jsonb, '[{"fecha": "2026-01-01", "accion": "Asignación inicial", "cliente": "Áridos del Sur", "ubicacion": "Base Operativa — Timbúes", "estado": "reservado"}]'::jsonb, 'no', '', ''),
  ('C-55', 'ACOSTA SERVICIOS SRL', 'Oficina', '20''', 'empresa', 'al_dia', '', 'Base Operativa — Timbúes', -32.6626, -60.7916, NULL, NULL, '$ 250.000', 'Unidad C-55 dada de alta en Base Timbúes.', '', '[]'::jsonb, '[{"fecha": "2026-03-01", "accion": "Alta de unidad", "cliente": "-", "ubicacion": "Base Operativa — Timbúes", "estado": "empresa"}]'::jsonb, 'no', '', '')
ON CONFLICT (code) DO UPDATE SET
    proveedor = EXCLUDED.proveedor,
    tipo = EXCLUDED.tipo,
    medida = EXCLUDED.medida,
    estado = EXCLUDED.estado,
    pago = EXCLUDED.pago,
    cliente = EXCLUDED.cliente,
    ubicacion = EXCLUDED.ubicacion,
    lat = EXCLUDED.lat,
    lng = EXCLUDED.lng,
    entrega = EXCLUDED.entrega,
    retiro = EXCLUDED.retiro,
    monto = EXCLUDED.monto,
    obs_entrega = EXCLUDED.obs_entrega,
    obs_retiro = EXCLUDED.obs_retiro,
    tareas = EXCLUDED.tareas,
    historial = EXCLUDED.historial,
    traslado = EXCLUDED.traslado,
    traslado_monto = EXCLUDED.traslado_monto,
    traslado_horas = EXCLUDED.traslado_horas,
    updated_at = timezone('utc'::text, now());

SELECT setval('public.contenedores_id_seq', (SELECT COALESCE(MAX(id), 1) FROM public.contenedores));

-- 10. CARGA INICIAL DE SEGUIMIENTO & TRAZABILIDAD
INSERT INTO public.seguimiento_contenedores (id, code, tipo, medida, proveedor, cliente, fecha_salida, hora_salida, destino, fecha_entrada, hora_entrada, retiro_estimado, estado_movimiento, traslado, traslado_monto, traslado_horas, observaciones, remito_numero, usuario)
SELECT 
    'seg_init_' || c.code AS id,
    c.code, c.tipo, c.medida, c.proveedor, c.cliente,
    COALESCE(c.entrega, '2026-03-01'::date) AS fecha_salida,
    '08:30' AS hora_salida,
    c.ubicacion AS destino,
    NULL::date AS fecha_entrada,
    '' AS hora_entrada,
    COALESCE(c.retiro::text, '2026-09-30') AS retiro_estimado,
    'en_obra' AS estado_movimiento,
    c.traslado, c.traslado_monto, c.traslado_horas,
    'Salida inicial a obra asentada en sistema' AS observaciones,
    'REM-' || SUBSTRING(c.code FROM 3) || '-01' AS remito_numero,
    'admin' AS usuario
FROM public.contenedores c
WHERE c.estado = 'alquilado'
ON CONFLICT (id) DO UPDATE SET
    proveedor = EXCLUDED.proveedor,
    cliente = EXCLUDED.cliente,
    destino = EXCLUDED.destino,
    traslado = EXCLUDED.traslado,
    traslado_monto = EXCLUDED.traslado_monto,
    traslado_horas = EXCLUDED.traslado_horas;
