-- ========================================================================
-- SCHEMA SQL PARA SUPABASE — SISTEMA DE GESTIÓN DE CONTENEDORES SG MONTAJES
-- ========================================================================

-- 1. Tabla de Usuarios del Sistema
CREATE TABLE IF NOT EXISTS public.usuarios_contenedores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    nombre TEXT NOT NULL,
    email TEXT,
    role TEXT DEFAULT 'Operador Logística',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Tabla de Configuración de la Empresa
CREATE TABLE IF NOT EXISTS public.configuracion_contenedores (
    id BIGINT PRIMARY KEY DEFAULT 1,
    empresa TEXT NOT NULL DEFAULT 'SG MONTAJES S.R.L.',
    cuit TEXT NOT NULL DEFAULT '30-71602466-7',
    iva TEXT DEFAULT 'Responsable Inscripto',
    deposito_principal TEXT DEFAULT 'Depósito central — Sarandí',
    direccion TEXT DEFAULT 'Av. Mitre 3400, Sarandí, Avellaneda, Buenos Aires',
    email_notificaciones TEXT DEFAULT 'cotizaciones@sgmontajes.com.ar',
    telefono TEXT DEFAULT '(0341) 5890126',
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Tabla Principal de Contenedores y Flota
CREATE TABLE IF NOT EXISTS public.contenedores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT UNIQUE NOT NULL,
    tipo TEXT NOT NULL DEFAULT 'Obrador',
    medida TEXT NOT NULL DEFAULT '20''',
    estado TEXT NOT NULL DEFAULT 'empresa', -- empresa, alquilado, reservado, reparacion
    pago TEXT DEFAULT 'al_dia',           -- al_dia, pendiente, retrasado
    cliente TEXT DEFAULT '',
    ubicacion TEXT DEFAULT 'Depósito central — Sarandí',
    lat DOUBLE PRECISION DEFAULT -34.6850,
    lng DOUBLE PRECISION DEFAULT -58.3550,
    entrega DATE,
    retiro DATE,
    monto TEXT DEFAULT '$ 250.000',
    obs_entrega TEXT DEFAULT '',
    obs_retiro TEXT DEFAULT '',
    tareas JSONB DEFAULT '[]'::jsonb,
    historial JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Índices para búsquedas y estadísticas rápidas
CREATE INDEX IF NOT EXISTS idx_contenedores_id ON public.contenedores(id);
CREATE INDEX IF NOT EXISTS idx_contenedores_code ON public.contenedores(code);
CREATE INDEX IF NOT EXISTS idx_contenedores_estado ON public.contenedores(estado);
CREATE INDEX IF NOT EXISTS idx_contenedores_cliente ON public.contenedores(cliente);
CREATE INDEX IF NOT EXISTS idx_contenedores_retiro ON public.contenedores(retiro);

-- Habilitar Row Level Security (RLS)
ALTER TABLE public.usuarios_contenedores ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.configuracion_contenedores ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contenedores ENABLE ROW LEVEL SECURITY;

-- Políticas de acceso para API anónima / autenticada
CREATE POLICY "Acceso público lectura y escritura a Contenedores" 
ON public.contenedores FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Acceso público a Configuración" 
ON public.configuracion_contenedores FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Acceso público a Usuarios" 
ON public.usuarios_contenedores FOR ALL USING (true) WITH CHECK (true);

-- Insertar configuración inicial
INSERT INTO public.configuracion_contenedores (id, empresa, cuit, iva, deposito_principal, direccion, email_notificaciones, telefono)
VALUES (1, 'SG MONTAJES S.R.L.', '30-71602466-7', 'Responsable Inscripto', 'Depósito central — Sarandí', 'Av. Mitre 3400, Sarandí, Avellaneda, Buenos Aires', 'cotizaciones@sgmontajes.com.ar', '(0341) 5890126')
ON CONFLICT (id) DO NOTHING;

-- Insertar usuario administrador inicial
INSERT INTO public.usuarios_contenedores (id, username, password_hash, nombre, email, role)
VALUES 
    (1, 'melani', '123', 'Melani Grandi', 'melanidaiana28@gmail.com', 'Administrador'),
    (2, 'mel', '123', 'Mel', 'melanidaiana28@gmail.com', 'Administrador'),
    (3, 'admin', '123', 'Administrador General', 'cotizaciones@sgmontajes.com.ar', 'Administrador'),
    (4, 'logistica', '123', 'Depósito & Despacho', 'logistica@sgmontajes.com.ar', 'Operador Logística')
ON CONFLICT (id) DO NOTHING;
SELECT setval('public.usuarios_contenedores_id_seq', (SELECT COALESCE(MAX(id), 1) FROM public.usuarios_contenedores));

-- Insertar los 50 Contenedores Iniciales (C-101 a C-150)
INSERT INTO public.contenedores (code, tipo, medida, estado, pago, cliente, ubicacion, lat, lng, entrega, retiro, obs_entrega, obs_retiro, tareas, historial)
VALUES ('C-101', 'Oficina', '20'', 'alquilado', 'retrasado', 'Obra Puerto Norte', 'Av. Calchaquí 5600, Quilmes', -34.7415, -58.2733, '2026-04-21', '2026-09-20', '', '', '[]'::jsonb, '[{"fecha": "2026-04-21", "accion": "Asignación inicial", "cliente": "Obra Puerto Norte", "ubicacion": "Av. Calchaquí 5600, Quilmes", "estado": "alquilado"}]'::jsonb)
ON CONFLICT (code) DO NOTHING;
INSERT INTO public.contenedores (code, tipo, medida, estado, pago, cliente, ubicacion, lat, lng, entrega, retiro, obs_entrega, obs_retiro, tareas, historial)
VALUES ('C-102', 'Oficina', '10'', 'alquilado', 'al_dia', 'Ingeniería Delta', 'Av. Circunvalación 900, Luján', -34.5701, -59.1053, '2026-07-21', '2026-10-14', 'Entregado con 2 llaves, aire funcionando, piso sin marcas.', '', '["Sellar filtración de techo"]'::jsonb, '[{"fecha": "2026-07-21", "accion": "Asignación inicial", "cliente": "Ingeniería Delta", "ubicacion": "Av. Circunvalación 900, Luján", "estado": "alquilado"}]'::jsonb)
ON CONFLICT (code) DO NOTHING;
INSERT INTO public.contenedores (code, tipo, medida, estado, pago, cliente, ubicacion, lat, lng, entrega, retiro, obs_entrega, obs_retiro, tareas, historial)
VALUES ('C-103', 'Pañol', '20'', 'alquilado', 'al_dia', 'Consorcio Ruta 9', 'Av. Circunvalación 900, Luján', -34.5701, -59.1053, '2026-06-18', '2026-11-16', '', '', '[]'::jsonb, '[{"fecha": "2026-06-18", "accion": "Asignación inicial", "cliente": "Consorcio Ruta 9", "ubicacion": "Av. Circunvalación 900, Luján", "estado": "alquilado"}]'::jsonb)
ON CONFLICT (code) DO NOTHING;
INSERT INTO public.contenedores (code, tipo, medida, estado, pago, cliente, ubicacion, lat, lng, entrega, retiro, obs_entrega, obs_retiro, tareas, historial)
VALUES ('C-104', 'Comedor', '40'', 'alquilado', 'al_dia', 'Constructora Riolar', 'Ruta 6 Km 118, Cañuelas', -35.0501, -58.7594, '2025-12-19', '2026-11-02', 'Entregado con 2 llaves, aire funcionando, piso sin marcas.', '', '[]'::jsonb, '[{"fecha": "2025-12-19", "accion": "Asignación inicial", "cliente": "Constructora Riolar", "ubicacion": "Ruta 6 Km 118, Cañuelas", "estado": "alquilado"}]'::jsonb)
ON CONFLICT (code) DO NOTHING;
INSERT INTO public.contenedores (code, tipo, medida, estado, pago, cliente, ubicacion, lat, lng, entrega, retiro, obs_entrega, obs_retiro, tareas, historial)
VALUES ('C-105', 'Pañol', '40'', 'alquilado', 'retrasado', 'Metalúrgica Sanz', 'Ruta 6 Km 118, Cañuelas', -35.0501, -58.7594, '2026-05-21', '2026-09-23', '', '', '["Pintura exterior"]'::jsonb, '[{"fecha": "2026-05-21", "accion": "Asignación inicial", "cliente": "Metalúrgica Sanz", "ubicacion": "Ruta 6 Km 118, Cañuelas", "estado": "alquilado"}]'::jsonb)
ON CONFLICT (code) DO NOTHING;
INSERT INTO public.contenedores (code, tipo, medida, estado, pago, cliente, ubicacion, lat, lng, entrega, retiro, obs_entrega, obs_retiro, tareas, historial)
VALUES ('C-106', 'Pañol', '20'', 'alquilado', 'al_dia', 'Tecnorural SRL', 'Av. Calchaquí 5600, Quilmes', -34.7415, -58.2733, '2026-04-22', '2026-08-31', 'Entregado con 2 llaves, aire funcionando, piso sin marcas.', '', '["Cambiar aire acondicionado"]'::jsonb, '[{"fecha": "2026-04-22", "accion": "Asignación inicial", "cliente": "Tecnorural SRL", "ubicacion": "Av. Calchaquí 5600, Quilmes", "estado": "alquilado"}]'::jsonb)
ON CONFLICT (code) DO NOTHING;
INSERT INTO public.contenedores (code, tipo, medida, estado, pago, cliente, ubicacion, lat, lng, entrega, retiro, obs_entrega, obs_retiro, tareas, historial)
VALUES ('C-107', 'Comedor', '10'', 'alquilado', 'retrasado', 'Consorcio Ruta 9', 'Camino Centenario 2200, La Plata', -34.9021, -57.9789, '2026-03-30', '2026-09-29', '', '', '[]'::jsonb, '[{"fecha": "2026-03-30", "accion": "Asignación inicial", "cliente": "Consorcio Ruta 9", "ubicacion": "Camino Centenario 2200, La Plata", "estado": "alquilado"}]'::jsonb)
ON CONFLICT (code) DO NOTHING;
INSERT INTO public.contenedores (code, tipo, medida, estado, pago, cliente, ubicacion, lat, lng, entrega, retiro, obs_entrega, obs_retiro, tareas, historial)
VALUES ('C-108', 'Comedor', '10'', 'alquilado', 'al_dia', 'Tecnorural SRL', 'Av. Calchaquí 5600, Quilmes', -34.7415, -58.2733, '2026-04-05', '2026-09-21', 'Entregado con 2 llaves, aire funcionando, piso sin marcas.', '', '[]'::jsonb, '[{"fecha": "2026-04-05", "accion": "Asignación inicial", "cliente": "Tecnorural SRL", "ubicacion": "Av. Calchaquí 5600, Quilmes", "estado": "alquilado"}]'::jsonb)
ON CONFLICT (code) DO NOTHING;
INSERT INTO public.contenedores (code, tipo, medida, estado, pago, cliente, ubicacion, lat, lng, entrega, retiro, obs_entrega, obs_retiro, tareas, historial)
VALUES ('C-109', 'Oficina', '40'', 'empresa', 'al_dia', '', 'Depósito central — Sarandí', -34.6795, -58.3312, NULL, NULL, '', '', '[]'::jsonb, '[]'::jsonb)
ON CONFLICT (code) DO NOTHING;
INSERT INTO public.contenedores (code, tipo, medida, estado, pago, cliente, ubicacion, lat, lng, entrega, retiro, obs_entrega, obs_retiro, tareas, historial)
VALUES ('C-110', 'Comedor', '10'', 'reservado', 'al_dia', 'Áridos del Sur', 'Depósito central — Sarandí', -34.6795, -58.3312, NULL, NULL, '', '', '["Sellar filtración de techo"]'::jsonb, '[{"fecha": "2026-01-01", "accion": "Asignación inicial", "cliente": "Áridos del Sur", "ubicacion": "Depósito central — Sarandí", "estado": "reservado"}]'::jsonb)
ON CONFLICT (code) DO NOTHING;
INSERT INTO public.contenedores (code, tipo, medida, estado, pago, cliente, ubicacion, lat, lng, entrega, retiro, obs_entrega, obs_retiro, tareas, historial)
VALUES ('C-111', 'Pañol', '10'', 'empresa', 'al_dia', '', 'Depósito central — Sarandí', -34.6795, -58.3312, NULL, NULL, '', '', '[]'::jsonb, '[]'::jsonb)
ON CONFLICT (code) DO NOTHING;
INSERT INTO public.contenedores (code, tipo, medida, estado, pago, cliente, ubicacion, lat, lng, entrega, retiro, obs_entrega, obs_retiro, tareas, historial)
VALUES ('C-112', 'Comedor', '20'', 'alquilado', 'al_dia', 'Ingeniería Delta', 'Av. Calchaquí 5600, Quilmes', -34.7415, -58.2733, '2026-03-12', '2026-09-23', '', '', '["Limpieza profunda", "Pintura exterior"]'::jsonb, '[{"fecha": "2026-03-12", "accion": "Asignación inicial", "cliente": "Ingeniería Delta", "ubicacion": "Av. Calchaquí 5600, Quilmes", "estado": "alquilado"}]'::jsonb)
ON CONFLICT (code) DO NOTHING;
INSERT INTO public.contenedores (code, tipo, medida, estado, pago, cliente, ubicacion, lat, lng, entrega, retiro, obs_entrega, obs_retiro, tareas, historial)
VALUES ('C-113', 'Comedor', '40'', 'empresa', 'al_dia', '', 'Depósito central — Sarandí', -34.6795, -58.3312, NULL, NULL, '', '', '[]'::jsonb, '[]'::jsonb)
ON CONFLICT (code) DO NOTHING;
INSERT INTO public.contenedores (code, tipo, medida, estado, pago, cliente, ubicacion, lat, lng, entrega, retiro, obs_entrega, obs_retiro, tareas, historial)
VALUES ('C-114', 'Comedor', '40'', 'alquilado', 'al_dia', 'Ingeniería Delta', 'Av. Circunvalación 900, Luján', -34.5701, -59.1053, '2025-12-11', '2026-09-08', '', '', '[]'::jsonb, '[{"fecha": "2025-12-11", "accion": "Asignación inicial", "cliente": "Ingeniería Delta", "ubicacion": "Av. Circunvalación 900, Luján", "estado": "alquilado"}]'::jsonb)
ON CONFLICT (code) DO NOTHING;
INSERT INTO public.contenedores (code, tipo, medida, estado, pago, cliente, ubicacion, lat, lng, entrega, retiro, obs_entrega, obs_retiro, tareas, historial)
VALUES ('C-115', 'Oficina', '20'', 'reparacion', 'al_dia', '', 'Taller propio — Sarandí', -34.6801, -58.3327, NULL, NULL, '', '', '["Reparar piso", "Cambiar cerradura"]'::jsonb, '[]'::jsonb)
ON CONFLICT (code) DO NOTHING;
INSERT INTO public.contenedores (code, tipo, medida, estado, pago, cliente, ubicacion, lat, lng, entrega, retiro, obs_entrega, obs_retiro, tareas, historial)
VALUES ('C-116', 'Comedor', '10'', 'alquilado', 'retrasado', 'Áridos del Sur', 'Ruta 6 Km 118, Cañuelas', -35.0501, -58.7594, '2026-04-05', '2026-09-13', '', '', '[]'::jsonb, '[{"fecha": "2026-04-05", "accion": "Asignación inicial", "cliente": "Áridos del Sur", "ubicacion": "Ruta 6 Km 118, Cañuelas", "estado": "alquilado"}]'::jsonb)
ON CONFLICT (code) DO NOTHING;
INSERT INTO public.contenedores (code, tipo, medida, estado, pago, cliente, ubicacion, lat, lng, entrega, retiro, obs_entrega, obs_retiro, tareas, historial)
VALUES ('C-117', 'Pañol', '40'', 'empresa', 'al_dia', '', 'Depósito central — Sarandí', -34.6795, -58.3312, NULL, NULL, '', '', '["Cambiar luminaria", "Cambiar cerradura"]'::jsonb, '[]'::jsonb)
ON CONFLICT (code) DO NOTHING;
INSERT INTO public.contenedores (code, tipo, medida, estado, pago, cliente, ubicacion, lat, lng, entrega, retiro, obs_entrega, obs_retiro, tareas, historial)
VALUES ('C-118', 'Comedor', '10'', 'reservado', 'al_dia', 'Ingeniería Delta', 'Depósito central — Sarandí', -34.6795, -58.3312, NULL, NULL, '', '', '["Reparar puerta"]'::jsonb, '[{"fecha": "2026-01-01", "accion": "Asignación inicial", "cliente": "Ingeniería Delta", "ubicacion": "Depósito central — Sarandí", "estado": "reservado"}]'::jsonb)
ON CONFLICT (code) DO NOTHING;
INSERT INTO public.contenedores (code, tipo, medida, estado, pago, cliente, ubicacion, lat, lng, entrega, retiro, obs_entrega, obs_retiro, tareas, historial)
VALUES ('C-119', 'Pañol', '40'', 'reparacion', 'al_dia', '', 'Taller propio — Sarandí', -34.6801, -58.3327, NULL, NULL, '', '', '[]'::jsonb, '[]'::jsonb)
ON CONFLICT (code) DO NOTHING;
INSERT INTO public.contenedores (code, tipo, medida, estado, pago, cliente, ubicacion, lat, lng, entrega, retiro, obs_entrega, obs_retiro, tareas, historial)
VALUES ('C-120', 'Oficina', '40'', 'empresa', 'al_dia', '', 'Depósito central — Sarandí', -34.6795, -58.3312, NULL, NULL, '', '', '[]'::jsonb, '[]'::jsonb)
ON CONFLICT (code) DO NOTHING;
INSERT INTO public.contenedores (code, tipo, medida, estado, pago, cliente, ubicacion, lat, lng, entrega, retiro, obs_entrega, obs_retiro, tareas, historial)
VALUES ('C-121', 'Pañol', '10'', 'reparacion', 'al_dia', '', 'Taller propio — Sarandí', -34.6801, -58.3327, NULL, NULL, '', '', '[]'::jsonb, '[]'::jsonb)
ON CONFLICT (code) DO NOTHING;
INSERT INTO public.contenedores (code, tipo, medida, estado, pago, cliente, ubicacion, lat, lng, entrega, retiro, obs_entrega, obs_retiro, tareas, historial)
VALUES ('C-122', 'Comedor', '10'', 'reservado', 'al_dia', 'Minera Cerro Azul', 'Depósito central — Sarandí', -34.6795, -58.3312, NULL, NULL, '', '', '[]'::jsonb, '[{"fecha": "2026-01-01", "accion": "Asignación inicial", "cliente": "Minera Cerro Azul", "ubicacion": "Depósito central — Sarandí", "estado": "reservado"}]'::jsonb)
ON CONFLICT (code) DO NOTHING;
INSERT INTO public.contenedores (code, tipo, medida, estado, pago, cliente, ubicacion, lat, lng, entrega, retiro, obs_entrega, obs_retiro, tareas, historial)
VALUES ('C-123', 'Comedor', '20'', 'alquilado', 'al_dia', 'Obra Vial Km 42', 'Parque Industrial Tigre, Nave 3', -34.4198, -58.6032, '2026-02-01', '2026-08-26', '', '', '[]'::jsonb, '[{"fecha": "2026-02-01", "accion": "Asignación inicial", "cliente": "Obra Vial Km 42", "ubicacion": "Parque Industrial Tigre, Nave 3", "estado": "alquilado"}]'::jsonb)
ON CONFLICT (code) DO NOTHING;
INSERT INTO public.contenedores (code, tipo, medida, estado, pago, cliente, ubicacion, lat, lng, entrega, retiro, obs_entrega, obs_retiro, tareas, historial)
VALUES ('C-124', 'Oficina', '10'', 'alquilado', 'al_dia', 'Ingeniería Delta', 'Puerto Nuevo, Dársena D, CABA', -34.5723, -58.3708, '2025-12-18', '2026-08-28', 'Entregado con 2 llaves, aire funcionando, piso sin marcas.', '', '["Pintura exterior"]'::jsonb, '[{"fecha": "2025-12-18", "accion": "Asignación inicial", "cliente": "Ingeniería Delta", "ubicacion": "Puerto Nuevo, Dársena D, CABA", "estado": "alquilado"}]'::jsonb)
ON CONFLICT (code) DO NOTHING;
INSERT INTO public.contenedores (code, tipo, medida, estado, pago, cliente, ubicacion, lat, lng, entrega, retiro, obs_entrega, obs_retiro, tareas, historial)
VALUES ('C-125', 'Comedor', '20'', 'alquilado', 'al_dia', 'Minera Cerro Azul', 'Puerto Nuevo, Dársena D, CABA', -34.5723, -58.3708, '2025-12-24', '2026-09-22', 'Entregado con 2 llaves, aire funcionando, piso sin marcas.', '', '[]'::jsonb, '[{"fecha": "2025-12-24", "accion": "Asignación inicial", "cliente": "Minera Cerro Azul", "ubicacion": "Puerto Nuevo, Dársena D, CABA", "estado": "alquilado"}]'::jsonb)
ON CONFLICT (code) DO NOTHING;
INSERT INTO public.contenedores (code, tipo, medida, estado, pago, cliente, ubicacion, lat, lng, entrega, retiro, obs_entrega, obs_retiro, tareas, historial)
VALUES ('C-126', 'Comedor', '20'', 'alquilado', 'al_dia', 'Ingeniería Delta', 'Ruta 9 Km 42, Escobar', -34.3486, -58.7931, '2026-01-14', '2026-09-27', '', '', '["Limpieza profunda"]'::jsonb, '[{"fecha": "2026-01-14", "accion": "Asignación inicial", "cliente": "Ingeniería Delta", "ubicacion": "Ruta 9 Km 42, Escobar", "estado": "alquilado"}]'::jsonb)
ON CONFLICT (code) DO NOTHING;
INSERT INTO public.contenedores (code, tipo, medida, estado, pago, cliente, ubicacion, lat, lng, entrega, retiro, obs_entrega, obs_retiro, tareas, historial)
VALUES ('C-127', 'Pañol', '20'', 'alquilado', 'retrasado', 'Constructora Riolar', 'Ruta 9 Km 42, Escobar', -34.3486, -58.7931, '2026-03-27', '2026-08-20', '', '', '[]'::jsonb, '[{"fecha": "2026-03-27", "accion": "Asignación inicial", "cliente": "Constructora Riolar", "ubicacion": "Ruta 9 Km 42, Escobar", "estado": "alquilado"}]'::jsonb)
ON CONFLICT (code) DO NOTHING;
INSERT INTO public.contenedores (code, tipo, medida, estado, pago, cliente, ubicacion, lat, lng, entrega, retiro, obs_entrega, obs_retiro, tareas, historial)
VALUES ('C-128', 'Oficina', '20'', 'empresa', 'al_dia', '', 'Depósito central — Sarandí', -34.6795, -58.3312, NULL, NULL, '', '', '[]'::jsonb, '[]'::jsonb)
ON CONFLICT (code) DO NOTHING;
INSERT INTO public.contenedores (code, tipo, medida, estado, pago, cliente, ubicacion, lat, lng, entrega, retiro, obs_entrega, obs_retiro, tareas, historial)
VALUES ('C-129', 'Oficina', '40'', 'reparacion', 'al_dia', '', 'Taller propio — Sarandí', -34.6801, -58.3327, NULL, NULL, '', '', '["Cambiar cerradura"]'::jsonb, '[]'::jsonb)
ON CONFLICT (code) DO NOTHING;
INSERT INTO public.contenedores (code, tipo, medida, estado, pago, cliente, ubicacion, lat, lng, entrega, retiro, obs_entrega, obs_retiro, tareas, historial)
VALUES ('C-130', 'Pañol', '20'', 'alquilado', 'al_dia', 'Consorcio Ruta 9', 'Parque Industrial Tigre, Nave 3', -34.4198, -58.6032, '2025-12-11', '2026-10-14', '', '', '["Limpieza profunda"]'::jsonb, '[{"fecha": "2025-12-11", "accion": "Asignación inicial", "cliente": "Consorcio Ruta 9", "ubicacion": "Parque Industrial Tigre, Nave 3", "estado": "alquilado"}]'::jsonb)
ON CONFLICT (code) DO NOTHING;
INSERT INTO public.contenedores (code, tipo, medida, estado, pago, cliente, ubicacion, lat, lng, entrega, retiro, obs_entrega, obs_retiro, tareas, historial)
VALUES ('C-131', 'Pañol', '20'', 'empresa', 'al_dia', '', 'Depósito central — Sarandí', -34.6795, -58.3312, NULL, NULL, '', '', '[]'::jsonb, '[]'::jsonb)
ON CONFLICT (code) DO NOTHING;
INSERT INTO public.contenedores (code, tipo, medida, estado, pago, cliente, ubicacion, lat, lng, entrega, retiro, obs_entrega, obs_retiro, tareas, historial)
VALUES ('C-132', 'Pañol', '40'', 'alquilado', 'al_dia', 'Constructora Riolar', 'Ruta 9 Km 42, Escobar', -34.3486, -58.7931, '2025-12-18', '2026-09-02', '', '', '[]'::jsonb, '[{"fecha": "2025-12-18", "accion": "Asignación inicial", "cliente": "Constructora Riolar", "ubicacion": "Ruta 9 Km 42, Escobar", "estado": "alquilado"}]'::jsonb)
ON CONFLICT (code) DO NOTHING;
INSERT INTO public.contenedores (code, tipo, medida, estado, pago, cliente, ubicacion, lat, lng, entrega, retiro, obs_entrega, obs_retiro, tareas, historial)
VALUES ('C-133', 'Pañol', '10'', 'alquilado', 'al_dia', 'Tecnorural SRL', 'Av. Calchaquí 5600, Quilmes', -34.7415, -58.2733, '2026-07-01', '2026-11-06', 'Entregado con 2 llaves, aire funcionando, piso sin marcas.', '', '[]'::jsonb, '[{"fecha": "2026-07-01", "accion": "Asignación inicial", "cliente": "Tecnorural SRL", "ubicacion": "Av. Calchaquí 5600, Quilmes", "estado": "alquilado"}]'::jsonb)
ON CONFLICT (code) DO NOTHING;
INSERT INTO public.contenedores (code, tipo, medida, estado, pago, cliente, ubicacion, lat, lng, entrega, retiro, obs_entrega, obs_retiro, tareas, historial)
VALUES ('C-134', 'Comedor', '40'', 'empresa', 'al_dia', '', 'Depósito central — Sarandí', -34.6795, -58.3312, NULL, NULL, '', '', '["Sellar filtración de techo"]'::jsonb, '[]'::jsonb)
ON CONFLICT (code) DO NOTHING;
INSERT INTO public.contenedores (code, tipo, medida, estado, pago, cliente, ubicacion, lat, lng, entrega, retiro, obs_entrega, obs_retiro, tareas, historial)
VALUES ('C-135', 'Comedor', '20'', 'alquilado', 'al_dia', 'Obra Puerto Norte', 'Ruta 9 Km 42, Escobar', -34.3486, -58.7931, '2026-01-09', '2026-11-17', 'Entregado con 2 llaves, aire funcionando, piso sin marcas.', '', '[]'::jsonb, '[{"fecha": "2026-01-09", "accion": "Asignación inicial", "cliente": "Obra Puerto Norte", "ubicacion": "Ruta 9 Km 42, Escobar", "estado": "alquilado"}]'::jsonb)
ON CONFLICT (code) DO NOTHING;
INSERT INTO public.contenedores (code, tipo, medida, estado, pago, cliente, ubicacion, lat, lng, entrega, retiro, obs_entrega, obs_retiro, tareas, historial)
VALUES ('C-136', 'Pañol', '20'', 'reparacion', 'al_dia', '', 'Taller propio — Sarandí', -34.6801, -58.3327, NULL, NULL, '', '', '[]'::jsonb, '[]'::jsonb)
ON CONFLICT (code) DO NOTHING;
INSERT INTO public.contenedores (code, tipo, medida, estado, pago, cliente, ubicacion, lat, lng, entrega, retiro, obs_entrega, obs_retiro, tareas, historial)
VALUES ('C-137', 'Oficina', '20'', 'alquilado', 'al_dia', 'Tecnorural SRL', 'Av. Calchaquí 5600, Quilmes', -34.7415, -58.2733, '2026-01-20', '2026-09-23', 'Entregado con 2 llaves, aire funcionando, piso sin marcas.', '', '[]'::jsonb, '[{"fecha": "2026-01-20", "accion": "Asignación inicial", "cliente": "Tecnorural SRL", "ubicacion": "Av. Calchaquí 5600, Quilmes", "estado": "alquilado"}]'::jsonb)
ON CONFLICT (code) DO NOTHING;
INSERT INTO public.contenedores (code, tipo, medida, estado, pago, cliente, ubicacion, lat, lng, entrega, retiro, obs_entrega, obs_retiro, tareas, historial)
VALUES ('C-138', 'Oficina', '20'', 'alquilado', 'al_dia', 'Ingeniería Delta', 'Av. Calchaquí 5600, Quilmes', -34.7415, -58.2733, '2026-01-29', '2026-09-15', 'Entregado con 2 llaves, aire funcionando, piso sin marcas.', '', '[]'::jsonb, '[{"fecha": "2026-01-29", "accion": "Asignación inicial", "cliente": "Ingeniería Delta", "ubicacion": "Av. Calchaquí 5600, Quilmes", "estado": "alquilado"}]'::jsonb)
ON CONFLICT (code) DO NOTHING;
INSERT INTO public.contenedores (code, tipo, medida, estado, pago, cliente, ubicacion, lat, lng, entrega, retiro, obs_entrega, obs_retiro, tareas, historial)
VALUES ('C-139', 'Oficina', '10'', 'empresa', 'al_dia', '', 'Depósito central — Sarandí', -34.6795, -58.3312, NULL, NULL, '', '', '[]'::jsonb, '[]'::jsonb)
ON CONFLICT (code) DO NOTHING;
INSERT INTO public.contenedores (code, tipo, medida, estado, pago, cliente, ubicacion, lat, lng, entrega, retiro, obs_entrega, obs_retiro, tareas, historial)
VALUES ('C-140', 'Pañol', '10'', 'alquilado', 'al_dia', 'Minera Cerro Azul', 'Parque Industrial Tigre, Nave 3', -34.4198, -58.6032, '2026-05-25', '2026-08-21', '', '', '[]'::jsonb, '[{"fecha": "2026-05-25", "accion": "Asignación inicial", "cliente": "Minera Cerro Azul", "ubicacion": "Parque Industrial Tigre, Nave 3", "estado": "alquilado"}]'::jsonb)
ON CONFLICT (code) DO NOTHING;
INSERT INTO public.contenedores (code, tipo, medida, estado, pago, cliente, ubicacion, lat, lng, entrega, retiro, obs_entrega, obs_retiro, tareas, historial)
VALUES ('C-141', 'Oficina', '20'', 'reservado', 'al_dia', 'Minera Cerro Azul', 'Depósito central — Sarandí', -34.6795, -58.3312, NULL, NULL, '', '', '[]'::jsonb, '[{"fecha": "2026-01-01", "accion": "Asignación inicial", "cliente": "Minera Cerro Azul", "ubicacion": "Depósito central — Sarandí", "estado": "reservado"}]'::jsonb)
ON CONFLICT (code) DO NOTHING;
INSERT INTO public.contenedores (code, tipo, medida, estado, pago, cliente, ubicacion, lat, lng, entrega, retiro, obs_entrega, obs_retiro, tareas, historial)
VALUES ('C-142', 'Pañol', '20'', 'alquilado', 'al_dia', 'Ingeniería Delta', 'Ruta 6 Km 118, Cañuelas', -35.0501, -58.7594, '2026-01-17', '2026-11-09', '', '', '[]'::jsonb, '[{"fecha": "2026-01-17", "accion": "Asignación inicial", "cliente": "Ingeniería Delta", "ubicacion": "Ruta 6 Km 118, Cañuelas", "estado": "alquilado"}]'::jsonb)
ON CONFLICT (code) DO NOTHING;
INSERT INTO public.contenedores (code, tipo, medida, estado, pago, cliente, ubicacion, lat, lng, entrega, retiro, obs_entrega, obs_retiro, tareas, historial)
VALUES ('C-143', 'Pañol', '20'', 'alquilado', 'al_dia', 'Ingeniería Delta', 'Parque Industrial Pilar, Lote 7', -34.4587, -58.9142, '2026-08-05', '2026-10-21', 'Entregado con 2 llaves, aire funcionando, piso sin marcas.', '', '[]'::jsonb, '[{"fecha": "2026-08-05", "accion": "Asignación inicial", "cliente": "Ingeniería Delta", "ubicacion": "Parque Industrial Pilar, Lote 7", "estado": "alquilado"}]'::jsonb)
ON CONFLICT (code) DO NOTHING;
INSERT INTO public.contenedores (code, tipo, medida, estado, pago, cliente, ubicacion, lat, lng, entrega, retiro, obs_entrega, obs_retiro, tareas, historial)
VALUES ('C-144', 'Comedor', '10'', 'alquilado', 'retrasado', 'Ingeniería Delta', 'Ruta 9 Km 42, Escobar', -34.3486, -58.7931, '2025-12-17', '2026-10-25', 'Entregado con 2 llaves, aire funcionando, piso sin marcas.', '', '["Pintura exterior"]'::jsonb, '[{"fecha": "2025-12-17", "accion": "Asignación inicial", "cliente": "Ingeniería Delta", "ubicacion": "Ruta 9 Km 42, Escobar", "estado": "alquilado"}]'::jsonb)
ON CONFLICT (code) DO NOTHING;
INSERT INTO public.contenedores (code, tipo, medida, estado, pago, cliente, ubicacion, lat, lng, entrega, retiro, obs_entrega, obs_retiro, tareas, historial)
VALUES ('C-145', 'Pañol', '10'', 'empresa', 'al_dia', '', 'Depósito central — Sarandí', -34.6795, -58.3312, NULL, NULL, '', '', '[]'::jsonb, '[]'::jsonb)
ON CONFLICT (code) DO NOTHING;
INSERT INTO public.contenedores (code, tipo, medida, estado, pago, cliente, ubicacion, lat, lng, entrega, retiro, obs_entrega, obs_retiro, tareas, historial)
VALUES ('C-146', 'Pañol', '10'', 'alquilado', 'al_dia', 'Constructora Riolar', 'Parque Industrial Pilar, Lote 7', -34.4587, -58.9142, '2026-06-23', '2026-10-18', 'Entregado con 2 llaves, aire funcionando, piso sin marcas.', '', '[]'::jsonb, '[{"fecha": "2026-06-23", "accion": "Asignación inicial", "cliente": "Constructora Riolar", "ubicacion": "Parque Industrial Pilar, Lote 7", "estado": "alquilado"}]'::jsonb)
ON CONFLICT (code) DO NOTHING;
INSERT INTO public.contenedores (code, tipo, medida, estado, pago, cliente, ubicacion, lat, lng, entrega, retiro, obs_entrega, obs_retiro, tareas, historial)
VALUES ('C-147', 'Pañol', '20'', 'alquilado', 'al_dia', 'Metalúrgica Sanz', 'Ruta 6 Km 118, Cañuelas', -35.0501, -58.7594, '2026-02-19', '2026-08-27', 'Entregado con 2 llaves, aire funcionando, piso sin marcas.', '', '["Reparar aire acondicionado", "Revisión eléctrica"]'::jsonb, '[{"fecha": "2026-02-19", "accion": "Asignación inicial", "cliente": "Metalúrgica Sanz", "ubicacion": "Ruta 6 Km 118, Cañuelas", "estado": "alquilado"}]'::jsonb)
ON CONFLICT (code) DO NOTHING;
INSERT INTO public.contenedores (code, tipo, medida, estado, pago, cliente, ubicacion, lat, lng, entrega, retiro, obs_entrega, obs_retiro, tareas, historial)
VALUES ('C-148', 'Comedor', '40'', 'alquilado', 'al_dia', 'Obra Puerto Norte', 'Av. Mitre 3400, Avellaneda', -34.6634, -58.3651, '2026-03-02', '2026-08-29', '', '', '[]'::jsonb, '[{"fecha": "2026-03-02", "accion": "Asignación inicial", "cliente": "Obra Puerto Norte", "ubicacion": "Av. Mitre 3400, Avellaneda", "estado": "alquilado"}]'::jsonb)
ON CONFLICT (code) DO NOTHING;
INSERT INTO public.contenedores (code, tipo, medida, estado, pago, cliente, ubicacion, lat, lng, entrega, retiro, obs_entrega, obs_retiro, tareas, historial)
VALUES ('C-149', 'Comedor', '20'', 'empresa', 'al_dia', '', 'Depósito central — Sarandí', -34.6795, -58.3312, NULL, NULL, '', '', '[]'::jsonb, '[]'::jsonb)
ON CONFLICT (code) DO NOTHING;
INSERT INTO public.contenedores (code, tipo, medida, estado, pago, cliente, ubicacion, lat, lng, entrega, retiro, obs_entrega, obs_retiro, tareas, historial)
VALUES ('C-150', 'Pañol', '20'', 'reservado', 'al_dia', 'Áridos del Sur', 'Depósito central — Sarandí', -34.6795, -58.3312, NULL, NULL, '', '', '["Limpieza profunda"]'::jsonb, '[{"fecha": "2026-01-01", "accion": "Asignación inicial", "cliente": "Áridos del Sur", "ubicacion": "Depósito central — Sarandí", "estado": "reservado"}]'::jsonb)
ON CONFLICT (code) DO NOTHING;


-- Ajustar la secuencia de IDs correlativos al número máximo cargado
SELECT setval('public.contenedores_id_seq', (SELECT COALESCE(MAX(id), 1) FROM public.contenedores));
